version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"  #  backend
      - "3000:3000"  #  frontend
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000